"""Add ai_verdict to Submission

Revision ID: 80af6777b1a1
Revises: 41a9b8d763c3
Create Date: 2026-05-13 14:02:22.478391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80af6777b1a1'
down_revision: Union[str, Sequence[str], None] = '41a9b8d763c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('ai_verdict', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'ai_verdict')
    # ### end Alembic commands ###
